// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doozer-msg.proto

package proto;

public final class DoozerMsg {
  private DoozerMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 tag = 1;
    boolean hasTag();
    int getTag();
    
    // optional .proto.Request.Verb verb = 2;
    boolean hasVerb();
    proto.DoozerMsg.Request.Verb getVerb();
    
    // optional string path = 4;
    boolean hasPath();
    String getPath();
    
    // optional bytes value = 5;
    boolean hasValue();
    com.google.protobuf.ByteString getValue();
    
    // optional int32 other_tag = 6;
    boolean hasOtherTag();
    int getOtherTag();
    
    // optional int32 offset = 7;
    boolean hasOffset();
    int getOffset();
    
    // optional int32 limit = 8;
    boolean hasLimit();
    int getLimit();
    
    // optional int64 rev = 9;
    boolean hasRev();
    long getRev();
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.DoozerMsg.internal_static_proto_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.DoozerMsg.internal_static_proto_Request_fieldAccessorTable;
    }
    
    public enum Verb
        implements com.google.protobuf.ProtocolMessageEnum {
      GET(0, 1),
      SET(1, 2),
      DEL(2, 3),
      ESET(3, 4),
      REV(4, 5),
      WAIT(5, 6),
      NOP(6, 7),
      WATCH(7, 8),
      WALK(8, 9),
      CANCEL(9, 10),
      GETDIR(10, 14),
      STAT(11, 16),
      ;
      
      public static final int GET_VALUE = 1;
      public static final int SET_VALUE = 2;
      public static final int DEL_VALUE = 3;
      public static final int ESET_VALUE = 4;
      public static final int REV_VALUE = 5;
      public static final int WAIT_VALUE = 6;
      public static final int NOP_VALUE = 7;
      public static final int WATCH_VALUE = 8;
      public static final int WALK_VALUE = 9;
      public static final int CANCEL_VALUE = 10;
      public static final int GETDIR_VALUE = 14;
      public static final int STAT_VALUE = 16;
      
      
      public final int getNumber() { return value; }
      
      public static Verb valueOf(int value) {
        switch (value) {
          case 1: return GET;
          case 2: return SET;
          case 3: return DEL;
          case 4: return ESET;
          case 5: return REV;
          case 6: return WAIT;
          case 7: return NOP;
          case 8: return WATCH;
          case 9: return WALK;
          case 10: return CANCEL;
          case 14: return GETDIR;
          case 16: return STAT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Verb>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Verb>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Verb>() {
              public Verb findValueByNumber(int number) {
                return Verb.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.DoozerMsg.Request.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Verb[] VALUES = {
        GET, SET, DEL, ESET, REV, WAIT, NOP, WATCH, WALK, CANCEL, GETDIR, STAT, 
      };
      
      public static Verb valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Verb(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:proto.Request.Verb)
    }
    
    private int bitField0_;
    // optional int32 tag = 1;
    public static final int TAG_FIELD_NUMBER = 1;
    private int tag_;
    public boolean hasTag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTag() {
      return tag_;
    }
    
    // optional .proto.Request.Verb verb = 2;
    public static final int VERB_FIELD_NUMBER = 2;
    private proto.DoozerMsg.Request.Verb verb_;
    public boolean hasVerb() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public proto.DoozerMsg.Request.Verb getVerb() {
      return verb_;
    }
    
    // optional string path = 4;
    public static final int PATH_FIELD_NUMBER = 4;
    private Object path_;
    public boolean hasPath() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPath() {
      Object ref = path_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          path_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPathBytes() {
      Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes value = 5;
    public static final int VALUE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }
    
    // optional int32 other_tag = 6;
    public static final int OTHER_TAG_FIELD_NUMBER = 6;
    private int otherTag_;
    public boolean hasOtherTag() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getOtherTag() {
      return otherTag_;
    }
    
    // optional int32 offset = 7;
    public static final int OFFSET_FIELD_NUMBER = 7;
    private int offset_;
    public boolean hasOffset() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getOffset() {
      return offset_;
    }
    
    // optional int32 limit = 8;
    public static final int LIMIT_FIELD_NUMBER = 8;
    private int limit_;
    public boolean hasLimit() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public int getLimit() {
      return limit_;
    }
    
    // optional int64 rev = 9;
    public static final int REV_FIELD_NUMBER = 9;
    private long rev_;
    public boolean hasRev() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public long getRev() {
      return rev_;
    }
    
    private void initFields() {
      tag_ = 0;
      verb_ = proto.DoozerMsg.Request.Verb.GET;
      path_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
      otherTag_ = 0;
      offset_ = 0;
      limit_ = 0;
      rev_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, tag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, verb_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getPathBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, value_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, otherTag_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, offset_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(8, limit_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(9, rev_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, tag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, verb_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPathBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, value_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, otherTag_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, offset_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, limit_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, rev_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static proto.DoozerMsg.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.DoozerMsg.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.DoozerMsg.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.DoozerMsg.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.DoozerMsg.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.DoozerMsg.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.DoozerMsg.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.DoozerMsg.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.DoozerMsg.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.DoozerMsg.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.DoozerMsg.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.DoozerMsg.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.DoozerMsg.internal_static_proto_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.DoozerMsg.internal_static_proto_Request_fieldAccessorTable;
      }
      
      // Construct using proto.DoozerMsg.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        tag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        verb_ = proto.DoozerMsg.Request.Verb.GET;
        bitField0_ = (bitField0_ & ~0x00000002);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        otherTag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        offset_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        limit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        rev_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.DoozerMsg.Request.getDescriptor();
      }
      
      public proto.DoozerMsg.Request getDefaultInstanceForType() {
        return proto.DoozerMsg.Request.getDefaultInstance();
      }
      
      public proto.DoozerMsg.Request build() {
        proto.DoozerMsg.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private proto.DoozerMsg.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        proto.DoozerMsg.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public proto.DoozerMsg.Request buildPartial() {
        proto.DoozerMsg.Request result = new proto.DoozerMsg.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tag_ = tag_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.verb_ = verb_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.path_ = path_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.otherTag_ = otherTag_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.offset_ = offset_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.limit_ = limit_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.rev_ = rev_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.DoozerMsg.Request) {
          return mergeFrom((proto.DoozerMsg.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(proto.DoozerMsg.Request other) {
        if (other == proto.DoozerMsg.Request.getDefaultInstance()) return this;
        if (other.hasTag()) {
          setTag(other.getTag());
        }
        if (other.hasVerb()) {
          setVerb(other.getVerb());
        }
        if (other.hasPath()) {
          setPath(other.getPath());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasOtherTag()) {
          setOtherTag(other.getOtherTag());
        }
        if (other.hasOffset()) {
          setOffset(other.getOffset());
        }
        if (other.hasLimit()) {
          setLimit(other.getLimit());
        }
        if (other.hasRev()) {
          setRev(other.getRev());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              tag_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              proto.DoozerMsg.Request.Verb value = proto.DoozerMsg.Request.Verb.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                verb_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              path_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              value_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              otherTag_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              offset_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              limit_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000080;
              rev_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 tag = 1;
      private int tag_ ;
      public boolean hasTag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTag() {
        return tag_;
      }
      public Builder setTag(int value) {
        bitField0_ |= 0x00000001;
        tag_ = value;
        onChanged();
        return this;
      }
      public Builder clearTag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tag_ = 0;
        onChanged();
        return this;
      }
      
      // optional .proto.Request.Verb verb = 2;
      private proto.DoozerMsg.Request.Verb verb_ = proto.DoozerMsg.Request.Verb.GET;
      public boolean hasVerb() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public proto.DoozerMsg.Request.Verb getVerb() {
        return verb_;
      }
      public Builder setVerb(proto.DoozerMsg.Request.Verb value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        verb_ = value;
        onChanged();
        return this;
      }
      public Builder clearVerb() {
        bitField0_ = (bitField0_ & ~0x00000002);
        verb_ = proto.DoozerMsg.Request.Verb.GET;
        onChanged();
        return this;
      }
      
      // optional string path = 4;
      private Object path_ = "";
      public boolean hasPath() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPath() {
        Object ref = path_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        path_ = value;
        onChanged();
        return this;
      }
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000004);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      void setPath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        path_ = value;
        onChanged();
      }
      
      // optional bytes value = 5;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      
      // optional int32 other_tag = 6;
      private int otherTag_ ;
      public boolean hasOtherTag() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getOtherTag() {
        return otherTag_;
      }
      public Builder setOtherTag(int value) {
        bitField0_ |= 0x00000010;
        otherTag_ = value;
        onChanged();
        return this;
      }
      public Builder clearOtherTag() {
        bitField0_ = (bitField0_ & ~0x00000010);
        otherTag_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 offset = 7;
      private int offset_ ;
      public boolean hasOffset() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getOffset() {
        return offset_;
      }
      public Builder setOffset(int value) {
        bitField0_ |= 0x00000020;
        offset_ = value;
        onChanged();
        return this;
      }
      public Builder clearOffset() {
        bitField0_ = (bitField0_ & ~0x00000020);
        offset_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 limit = 8;
      private int limit_ ;
      public boolean hasLimit() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public int getLimit() {
        return limit_;
      }
      public Builder setLimit(int value) {
        bitField0_ |= 0x00000040;
        limit_ = value;
        onChanged();
        return this;
      }
      public Builder clearLimit() {
        bitField0_ = (bitField0_ & ~0x00000040);
        limit_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 rev = 9;
      private long rev_ ;
      public boolean hasRev() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public long getRev() {
        return rev_;
      }
      public Builder setRev(long value) {
        bitField0_ |= 0x00000080;
        rev_ = value;
        onChanged();
        return this;
      }
      public Builder clearRev() {
        bitField0_ = (bitField0_ & ~0x00000080);
        rev_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.Request)
  }
  
  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional int32 tag = 1;
    boolean hasTag();
    int getTag();
    
    // optional int32 flags = 2;
    boolean hasFlags();
    int getFlags();
    
    // optional int64 rev = 3;
    boolean hasRev();
    long getRev();
    
    // optional string path = 5;
    boolean hasPath();
    String getPath();
    
    // optional bytes value = 6;
    boolean hasValue();
    com.google.protobuf.ByteString getValue();
    
    // optional int32 len = 8;
    boolean hasLen();
    int getLen();
    
    // optional .proto.Response.Err err_code = 100;
    boolean hasErrCode();
    proto.DoozerMsg.Response.Err getErrCode();
    
    // optional string err_detail = 101;
    boolean hasErrDetail();
    String getErrDetail();
  }
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(Builder builder) {
      super(builder);
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.DoozerMsg.internal_static_proto_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.DoozerMsg.internal_static_proto_Response_fieldAccessorTable;
    }
    
    public enum Err
        implements com.google.protobuf.ProtocolMessageEnum {
      OTHER(0, 127),
      TAG_IN_USE(1, 1),
      UNKNOWN_VERB(2, 2),
      REDIRECT(3, 3),
      TOO_LATE(4, 4),
      REV_MISMATCH(5, 5),
      BAD_PATH(6, 6),
      MISSING_ARG(7, 7),
      NOTDIR(8, 20),
      ISDIR(9, 21),
      NOENT(10, 22),
      ;
      
      public static final int OTHER_VALUE = 127;
      public static final int TAG_IN_USE_VALUE = 1;
      public static final int UNKNOWN_VERB_VALUE = 2;
      public static final int REDIRECT_VALUE = 3;
      public static final int TOO_LATE_VALUE = 4;
      public static final int REV_MISMATCH_VALUE = 5;
      public static final int BAD_PATH_VALUE = 6;
      public static final int MISSING_ARG_VALUE = 7;
      public static final int NOTDIR_VALUE = 20;
      public static final int ISDIR_VALUE = 21;
      public static final int NOENT_VALUE = 22;
      
      
      public final int getNumber() { return value; }
      
      public static Err valueOf(int value) {
        switch (value) {
          case 127: return OTHER;
          case 1: return TAG_IN_USE;
          case 2: return UNKNOWN_VERB;
          case 3: return REDIRECT;
          case 4: return TOO_LATE;
          case 5: return REV_MISMATCH;
          case 6: return BAD_PATH;
          case 7: return MISSING_ARG;
          case 20: return NOTDIR;
          case 21: return ISDIR;
          case 22: return NOENT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Err>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Err>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Err>() {
              public Err findValueByNumber(int number) {
                return Err.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.DoozerMsg.Response.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Err[] VALUES = {
        OTHER, TAG_IN_USE, UNKNOWN_VERB, REDIRECT, TOO_LATE, REV_MISMATCH, BAD_PATH, MISSING_ARG, NOTDIR, ISDIR, NOENT, 
      };
      
      public static Err valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Err(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:proto.Response.Err)
    }
    
    private int bitField0_;
    // optional int32 tag = 1;
    public static final int TAG_FIELD_NUMBER = 1;
    private int tag_;
    public boolean hasTag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getTag() {
      return tag_;
    }
    
    // optional int32 flags = 2;
    public static final int FLAGS_FIELD_NUMBER = 2;
    private int flags_;
    public boolean hasFlags() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getFlags() {
      return flags_;
    }
    
    // optional int64 rev = 3;
    public static final int REV_FIELD_NUMBER = 3;
    private long rev_;
    public boolean hasRev() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getRev() {
      return rev_;
    }
    
    // optional string path = 5;
    public static final int PATH_FIELD_NUMBER = 5;
    private Object path_;
    public boolean hasPath() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getPath() {
      Object ref = path_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          path_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPathBytes() {
      Object ref = path_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes value = 6;
    public static final int VALUE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }
    
    // optional int32 len = 8;
    public static final int LEN_FIELD_NUMBER = 8;
    private int len_;
    public boolean hasLen() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getLen() {
      return len_;
    }
    
    // optional .proto.Response.Err err_code = 100;
    public static final int ERR_CODE_FIELD_NUMBER = 100;
    private proto.DoozerMsg.Response.Err errCode_;
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public proto.DoozerMsg.Response.Err getErrCode() {
      return errCode_;
    }
    
    // optional string err_detail = 101;
    public static final int ERR_DETAIL_FIELD_NUMBER = 101;
    private Object errDetail_;
    public boolean hasErrDetail() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getErrDetail() {
      Object ref = errDetail_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          errDetail_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrDetailBytes() {
      Object ref = errDetail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        errDetail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      tag_ = 0;
      flags_ = 0;
      rev_ = 0L;
      path_ = "";
      value_ = com.google.protobuf.ByteString.EMPTY;
      len_ = 0;
      errCode_ = proto.DoozerMsg.Response.Err.OTHER;
      errDetail_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, tag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, flags_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, rev_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getPathBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, value_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(8, len_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeEnum(100, errCode_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(101, getErrDetailBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, tag_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, flags_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, rev_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPathBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, value_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, len_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(100, errCode_.getNumber());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(101, getErrDetailBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static proto.DoozerMsg.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.DoozerMsg.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.DoozerMsg.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.DoozerMsg.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.DoozerMsg.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.DoozerMsg.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.DoozerMsg.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.DoozerMsg.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.DoozerMsg.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.DoozerMsg.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.DoozerMsg.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.DoozerMsg.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.DoozerMsg.internal_static_proto_Response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.DoozerMsg.internal_static_proto_Response_fieldAccessorTable;
      }
      
      // Construct using proto.DoozerMsg.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        tag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        flags_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        rev_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        path_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        len_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        errCode_ = proto.DoozerMsg.Response.Err.OTHER;
        bitField0_ = (bitField0_ & ~0x00000040);
        errDetail_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.DoozerMsg.Response.getDescriptor();
      }
      
      public proto.DoozerMsg.Response getDefaultInstanceForType() {
        return proto.DoozerMsg.Response.getDefaultInstance();
      }
      
      public proto.DoozerMsg.Response build() {
        proto.DoozerMsg.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private proto.DoozerMsg.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        proto.DoozerMsg.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public proto.DoozerMsg.Response buildPartial() {
        proto.DoozerMsg.Response result = new proto.DoozerMsg.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tag_ = tag_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.flags_ = flags_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rev_ = rev_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.path_ = path_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.len_ = len_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.errDetail_ = errDetail_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.DoozerMsg.Response) {
          return mergeFrom((proto.DoozerMsg.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(proto.DoozerMsg.Response other) {
        if (other == proto.DoozerMsg.Response.getDefaultInstance()) return this;
        if (other.hasTag()) {
          setTag(other.getTag());
        }
        if (other.hasFlags()) {
          setFlags(other.getFlags());
        }
        if (other.hasRev()) {
          setRev(other.getRev());
        }
        if (other.hasPath()) {
          setPath(other.getPath());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasLen()) {
          setLen(other.getLen());
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasErrDetail()) {
          setErrDetail(other.getErrDetail());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              tag_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              flags_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rev_ = input.readInt64();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              path_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000010;
              value_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000020;
              len_ = input.readInt32();
              break;
            }
            case 800: {
              int rawValue = input.readEnum();
              proto.DoozerMsg.Response.Err value = proto.DoozerMsg.Response.Err.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(100, rawValue);
              } else {
                bitField0_ |= 0x00000040;
                errCode_ = value;
              }
              break;
            }
            case 810: {
              bitField0_ |= 0x00000080;
              errDetail_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional int32 tag = 1;
      private int tag_ ;
      public boolean hasTag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getTag() {
        return tag_;
      }
      public Builder setTag(int value) {
        bitField0_ |= 0x00000001;
        tag_ = value;
        onChanged();
        return this;
      }
      public Builder clearTag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tag_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 flags = 2;
      private int flags_ ;
      public boolean hasFlags() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getFlags() {
        return flags_;
      }
      public Builder setFlags(int value) {
        bitField0_ |= 0x00000002;
        flags_ = value;
        onChanged();
        return this;
      }
      public Builder clearFlags() {
        bitField0_ = (bitField0_ & ~0x00000002);
        flags_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 rev = 3;
      private long rev_ ;
      public boolean hasRev() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getRev() {
        return rev_;
      }
      public Builder setRev(long value) {
        bitField0_ |= 0x00000004;
        rev_ = value;
        onChanged();
        return this;
      }
      public Builder clearRev() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rev_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string path = 5;
      private Object path_ = "";
      public boolean hasPath() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getPath() {
        Object ref = path_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        path_ = value;
        onChanged();
        return this;
      }
      public Builder clearPath() {
        bitField0_ = (bitField0_ & ~0x00000008);
        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      void setPath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        path_ = value;
        onChanged();
      }
      
      // optional bytes value = 6;
      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      
      // optional int32 len = 8;
      private int len_ ;
      public boolean hasLen() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getLen() {
        return len_;
      }
      public Builder setLen(int value) {
        bitField0_ |= 0x00000020;
        len_ = value;
        onChanged();
        return this;
      }
      public Builder clearLen() {
        bitField0_ = (bitField0_ & ~0x00000020);
        len_ = 0;
        onChanged();
        return this;
      }
      
      // optional .proto.Response.Err err_code = 100;
      private proto.DoozerMsg.Response.Err errCode_ = proto.DoozerMsg.Response.Err.OTHER;
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public proto.DoozerMsg.Response.Err getErrCode() {
        return errCode_;
      }
      public Builder setErrCode(proto.DoozerMsg.Response.Err value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        errCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000040);
        errCode_ = proto.DoozerMsg.Response.Err.OTHER;
        onChanged();
        return this;
      }
      
      // optional string err_detail = 101;
      private Object errDetail_ = "";
      public boolean hasErrDetail() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getErrDetail() {
        Object ref = errDetail_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          errDetail_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrDetail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        errDetail_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrDetail() {
        bitField0_ = (bitField0_ & ~0x00000080);
        errDetail_ = getDefaultInstance().getErrDetail();
        onChanged();
        return this;
      }
      void setErrDetail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        errDetail_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:proto.Response)
    }
    
    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.Response)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Response_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020doozer-msg.proto\022\005proto\"\225\002\n\007Request\022\013\n" +
      "\003tag\030\001 \001(\005\022!\n\004verb\030\002 \001(\0162\023.proto.Request" +
      ".Verb\022\014\n\004path\030\004 \001(\t\022\r\n\005value\030\005 \001(\014\022\021\n\tot" +
      "her_tag\030\006 \001(\005\022\016\n\006offset\030\007 \001(\005\022\r\n\005limit\030\010" +
      " \001(\005\022\013\n\003rev\030\t \001(\003\"~\n\004Verb\022\007\n\003GET\020\001\022\007\n\003SE" +
      "T\020\002\022\007\n\003DEL\020\003\022\010\n\004ESET\020\004\022\007\n\003REV\020\005\022\010\n\004WAIT\020" +
      "\006\022\007\n\003NOP\020\007\022\t\n\005WATCH\020\010\022\010\n\004WALK\020\t\022\n\n\006CANCE" +
      "L\020\n\022\n\n\006GETDIR\020\016\022\010\n\004STAT\020\020\"\274\002\n\010Response\022\013" +
      "\n\003tag\030\001 \001(\005\022\r\n\005flags\030\002 \001(\005\022\013\n\003rev\030\003 \001(\003\022" +
      "\014\n\004path\030\005 \001(\t\022\r\n\005value\030\006 \001(\014\022\013\n\003len\030\010 \001(",
      "\005\022%\n\010err_code\030d \001(\0162\023.proto.Response.Err" +
      "\022\022\n\nerr_detail\030e \001(\t\"\241\001\n\003Err\022\t\n\005OTHER\020\177\022" +
      "\016\n\nTAG_IN_USE\020\001\022\020\n\014UNKNOWN_VERB\020\002\022\014\n\010RED" +
      "IRECT\020\003\022\014\n\010TOO_LATE\020\004\022\020\n\014REV_MISMATCH\020\005\022" +
      "\014\n\010BAD_PATH\020\006\022\017\n\013MISSING_ARG\020\007\022\n\n\006NOTDIR" +
      "\020\024\022\t\n\005ISDIR\020\025\022\t\n\005NOENT\020\026"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_Request_descriptor,
              new java.lang.String[] { "Tag", "Verb", "Path", "Value", "OtherTag", "Offset", "Limit", "Rev", },
              proto.DoozerMsg.Request.class,
              proto.DoozerMsg.Request.Builder.class);
          internal_static_proto_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_Response_descriptor,
              new java.lang.String[] { "Tag", "Flags", "Rev", "Path", "Value", "Len", "ErrCode", "ErrDetail", },
              proto.DoozerMsg.Response.class,
              proto.DoozerMsg.Response.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
